kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kdm-course
  name: pod-reader
rules:
- apiGroups: [""] # "" indocates the core API group
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
